export { person, featuredProjects } from "./person";
export const PROFILE_PHOTO = "/images/profile.webp";
export { navLinks, navIcons } from "./nav";
export { dockApps } from "./dock";
export { projects } from "./projects";
export { techStack } from "./tech";
export { socials } from "./socials";
export { photosLinks, gallery } from "./photos";
export { locations } from "./locations";
export { INITIAL_Z_INDEX, WINDOW_CONFIG } from "./window";
export * from "./env";
