import {
  PROJECT_1_URL,
  PROJECT_1_GITHUB,
  PROJECT_2_URL,
  PROJECT_2_GITHUB,
  PROJECT_3_URL,
  PROJECT_3_GITHUB,
  PROJECT_4_URL,
  PROJECT_4_GITHUB,
} from "./env";

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "Krydo",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "Krydo Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Krydo is privacy-preserving identity infrastructure by Nishant Agarwal. Prove eligibility with zero-knowledge proofs and W3C verifiable credentials without revealing confidential data.",
            "154 tests. 3 contracts deployed on Sepolia. Circom circuits plus on-chain verification.",
            "Stack: Solidity, Hardhat, ZK proofs, Next.js, and Ethereum.",
          ],
        },
        {
          id: 2,
          name: "krydo.onrender.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_1_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "krydo.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/newtube.webp",
          imageMobUrl: "/projects/mobile/newtube-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_1_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 6,
      name: "BlockForge",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "BlockForge Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "BlockForge is a decentralized academic assessment platform. Lab submissions live on IPFS with content IDs stored on-chain, cutting storage cost by about 92%.",
            "Modular Solidity contracts, Express backend, React frontend, and MetaMask. Paper accepted at NetCrypt 2026.",
            "Live: blockchain-labeval.onrender.com",
          ],
        },
        {
          id: 2,
          name: "blockforge.onrender.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_2_URL,
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "blockforge.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/projects/snsta.webp",
          imageMobUrl: "/projects/mobile/snsta-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_2_GITHUB,
          position: "top-60 left-5",
        },
      ],
    },
    {
      id: 7,
      name: "CivicSense",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "CivicSense Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "CivicSense is on-chain civic issue reporting with hybrid storage: Supabase for speed, Sepolia for integrity.",
            "Gemini-assisted triage classifies reports. Citizens submit issues, admins track resolution on-chain.",
            "Stack: Solidity, Next.js, Supabase, Gemini, and Ethereum.",
          ],
        },
        {
          id: 2,
          name: "civicsense.vercel.app",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_3_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "civicsense.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/resume-ats.webp",
          imageMobUrl: "/projects/mobile/resume-ats-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_3_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 8,
      name: "TrustMesh",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 left-5",
      windowPosition: "top-[46vh] left-7",
      children: [
        {
          id: 1,
          name: "TrustMesh Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "TrustMesh is a business trust network on Stellar Soroban. Companies build on-chain reputation instead of relying on opaque off-chain scores.",
            "Smart contracts on Soroban, Next.js frontend, and a live reputation graph.",
            "Live: trust-mesh-taupe.vercel.app",
          ],
        },
        {
          id: 2,
          name: "trustmesh.vercel.app",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_4_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "trustmesh.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/docs-editor.webp",
          imageMobUrl: "/projects/mobile/docs-editor-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_4_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 4,
      name: "about-me.txt",
      icon: "/images/txt.webp",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      description: [
        "Hey! I'm Nishant Agarwal, a backend and blockchain engineer at Bennett University.",
        "I ship production systems: ZK identity (Krydo), on-chain assessment (BlockForge / NetCrypt 2026), and OSS merged into Hardhat, Hyperlane, FilOzone, and Mastra.",
        "Former Web3 intern at Digital South Trust. Finalist at LNMHacks 8.0. Top 20 at Kshitij 2026, IIT Kharagpur.",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.webp",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/trash-1.webp",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/images/trash-2.webp",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};
